### ISSUE TITLE
Sending emails with attachments. 

### ISSUE THREAD

**Issue by psihonavt** [jasonjoh/python_tutorial#3]
Not really related to python-tutorial, but related to using Outlook Mail REST API in python :) And I'd say that extending tutorial with answer to my question will be very beneficial (googling does not help me at all). 

So, I'm trying to use next API method: https://msdn.microsoft.com/office/office365/APi/mail-rest-operations#SendMessages. Sending messages without attachments works just fine, but I can not understand how to send message with attachments. According to docs, `Message` structure can contain array of `Attachments` with items of type https://msdn.microsoft.com/office/office365/APi/complex-types-for-mail-contacts-calendar#RESTAPIResourcesFileAttachment Problem is in the field `ContentBytes` -- it is impossible to dump bytes to JSON before sending request to this API method (actually dumping any BLOB to JSON is nonsense). 
How should we pass Attachments using REST API at all, and specifically using python `requests` (or any other library)?

Thanks.

**Comment by jasonjoh** [comment]
Ok, if you look a the [send_attachment](https://github.com/jasonjoh/python_tutorial/tree/send_attachment) branch that should show how to do it. I added a couple of small files (text and jpg) to the project, and I tested sending them both. I should note that doing this uncovered a bug in my original version of the `make_api_call` method! The `payload` parameter needs to be dumped to JSON before being sent to the `requests` library, like:

```
response = requests.patch(url, headers = headers, data = json.dumps(payload), params = parameters)
```

**Comment by psihonavt** [comment]
Thank you.

**Comment by shezankazi** [comment]
@psihonavt Would you mind posting your send_mail function here? Thanks!

**Comment by psihonavt** [comment]
In our code, we prepare the message payload as next:
```python
        message = {
            "Message": {
                "Subject": <SOME SUBJET>,
                "Body": {
                    "ContentType": "HTML",
                    "Content": <BODY CONTENT>
                },
                "ToRecipients": [
                    {
                        "EmailAddress": {
                            "Address": email
                        }
                    } for email in <LIST OF RECIPIENT EMAILS>
                ],
                "CcRecipients": [
                    {
                        "EmailAddress": {
                            "Address": email
                        }
                    } for email in <LIST OF CC EMAILS>
                ],
                "BccRecipients": [
                    {
                        "EmailAddress": {
                            "Address": email
                        }
                    } for email in <LIST OF BCC EMAILS>
                ],
                "Attachments": [
                    {
                        "@odata.type": "#Microsoft.OutlookServices.FileAttachment",
                        "ContentBytes": base64.encodestring(<ATTACHMENT.CONTENT>),
                        "ContentType": <ATTACHMENT.CONTENT_TYPE>,
                        "Name": <ATTACHMENT.NAME>,
                        "Size": <ATTACHMENT.FILE_NAME>
                    } for <ATTACHMENT> in <LIST OF ATTACHMENTS>
                ]},
            "SaveToSentItems": "true"
        }
```
Hope it helps.
