### ISSUE TITLE
Current response with JWT differs from one's expected in tutorial example

### ISSUE THREAD

**Issue by psihonavt** [jasonjoh/python_tutorial#4]
Hello,

Today, our auth code (which is based on this tutorials) for Outlook accounts started to crash, because JWT format had changed. Currently it looks like:

``` javascript
{
u'ver': u'2.0', 
u'aud': u'b27e9f81-dbc4-4d4a-923a-3eacaae45241', 
u'iss': u'https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0', 
u'at_hash': u'A9zHQW2pywcdHzwmqdcGpg', 
u'exp': 1456497726, 
u'tid': u'9188040d-6c67-4c5b-b112-36a304b66dad', 
u'iat': 1456411326, 
u'sub': u'AAAAAAAAAAAAAAAAAAAAAEd_FVIeg7D50-KulnCFDGo'
}
```

Fields `preferred_username` and `name` are absent. Quick googling gives nothing ... documentation on Microsoft's dev portal also does not display any updates. 
Can you shed some light on this?
Thanks a lot.

**Comment by jasonjoh** [comment]
Yes, Azure made a breaking change to the v2 endpoint, which they announced on [their blog](https://blogs.technet.microsoft.com/ad/2016/01/27/for-developers-important-upcoming-changes-to-the-v2-0-auth-protocol/).

Basically they don't return that field in the JWT unless you specifically request the `profile` scope in addition to the other scopes you request in the auth request. This notifies the user that you'll see their basic profile.

See this post: http://stackoverflow.com/questions/35605103/can-not-get-signed-in-email-using-office-365-rest-api/35605630.

I'll push a fix to the tutorial shortly.

**Comment by psihonavt** [comment]
Thanks a lot for pointing out on this API change!
