### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by begyy** [jasonjoh/python_tutorial#9]
![image](https://user-images.githubusercontent.com/44405438/50146878-96eecc80-02d6-11e9-81cb-0a26e4a80051.png)

**Comment by jasonjoh** [comment]
Closing this issue as I'm archiving this sample. We've retired the tutorial that this is based on and we're redirecting to the Microsoft Graph tutorial at https://docs.microsoft.com/graph/tutorials/python. The corresponding GitHub repo is https://github.com/microsoftgraph/msgraph-training-pythondjangoapp.
